### ISSUE TITLE
Logout

### ISSUE THREAD

**Issue by CubicDEVs** [braydondavis/Nerd-Gaming-Public#15]
When u do the command /logout it opens a bugged login panel.

screenshots: http://imgur.com/tkI4GYo,zYKngNE

**Comment by braydondavis** [comment]
Hello CubicDEVs,
Thank you for reporting this. It will be fixed in the next update. You can get the development version at https://github.com/braydondavis/Nerd-Gaming-Public/blob/development/resources/NGLogin/server.lua

Thank you,
xXMADEXx
